baseURL = 'https://hazembook.com/'
languageCode = 'en-us'
title = "hazembook"

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[params]
  # Set a single default variant
  # themeVariant = "relearn-dark"

  # Allow users to choose from a list (first is default)
  themeVariant = ["zen-dark", "zen-light", "relearn-dark", "relearn-light"]

defaultContentLanguage = 'en'

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en'
    languageName = 'English'
    title = 'My Website'
    weight = 1

  [languages.ar]
    contentDir = 'content/ar'
    languageCode = 'ar'
    languageDirection = 'rtl'
    languageName = 'Arabic'
    weight = 2
