baseURL = 'https://hazembook.com/'
languageCode = 'en-us'
title = "hazembook"

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[params]
  # Set a single default variant
  # themeVariant = "relearn-dark"

  # Allow users to choose from a list (first is default)
  themeVariant = ["zen-dark", "zen-light", "relearn-dark", "relearn-light"]

# Set the default language
defaultContentLanguage = "ar"

[languages]
  [languages.ar]
    languageName = "العربية" # Arabic Language Name
    languageCode = "ar"
    contentDir = "content/ar" # Content files for Arabic
    weight = 1
    rtl = true
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    contentDir = "content/en" # Content files for English
    weight = 2 # Order in language switcher (lower is first)
