baseURL = 'https://hazembook.com/'
title = "hazembook"
languageCode = 'ar'
defaultContentLanguage = 'ar'

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[params]
  themeVariant = ["zen-dark", "zen-light", "relearn-dark", "relearn-light"]

[languages]
  [languages.ar]
    contentDir = 'content/ar'
    languageCode = 'ar'
    languageDirection = 'rtl'
    languageName = 'Arabic'
    weight = 1
  
  [languages.en]
    contentDir = 'content/en'
    languageCode = 'en'
    languageName = 'English'
    weight = 2
